<dec f='llvm/llvm/lib/Support/regengine.inc' l='72' type='struct re_guts *'/>
<use f='llvm/llvm/lib/Support/regengine.inc' l='169' u='w' c='smatcher'/>
<use f='llvm/llvm/lib/Support/regengine.inc' l='210' u='r' c='smatcher'/>
<use f='llvm/llvm/lib/Support/regengine.inc' l='216' u='r' c='smatcher'/>
<use f='llvm/llvm/lib/Support/regengine.inc' l='275' u='r' c='smatcher'/>
<use f='llvm/llvm/lib/Support/regengine.inc' l='316' u='r' c='sdissect'/>
<use f='llvm/llvm/lib/Support/regengine.inc' l='319' u='r' c='sdissect'/>
<use f='llvm/llvm/lib/Support/regengine.inc' l='322' u='r' c='sdissect'/>
<use f='llvm/llvm/lib/Support/regengine.inc' l='323' u='r' c='sdissect'/>
<use f='llvm/llvm/lib/Support/regengine.inc' l='329' u='r' c='sdissect'/>
<use f='llvm/llvm/lib/Support/regengine.inc' l='429' u='r' c='sdissect'/>
<use f='llvm/llvm/lib/Support/regengine.inc' l='439' u='r' c='sdissect'/>
<use f='llvm/llvm/lib/Support/regengine.inc' l='440' u='r' c='sdissect'/>
<use f='llvm/llvm/lib/Support/regengine.inc' l='460' u='r' c='sdissect'/>
<use f='llvm/llvm/lib/Support/regengine.inc' l='465' u='r' c='sdissect'/>
<use f='llvm/llvm/lib/Support/regengine.inc' l='505' u='r' c='sbackref'/>
<use f='llvm/llvm/lib/Support/regengine.inc' l='516' u='r' c='sbackref'/>
<use f='llvm/llvm/lib/Support/regengine.inc' l='523' u='r' c='sbackref'/>
<use f='llvm/llvm/lib/Support/regengine.inc' l='531' u='r' c='sbackref'/>
<use f='llvm/llvm/lib/Support/regengine.inc' l='539' u='r' c='sbackref'/>
<use f='llvm/llvm/lib/Support/regengine.inc' l='550' u='r' c='sbackref'/>
<use f='llvm/llvm/lib/Support/regengine.inc' l='561' u='r' c='sbackref'/>
<use f='llvm/llvm/lib/Support/regengine.inc' l='565' u='r' c='sbackref'/>
<use f='llvm/llvm/lib/Support/regengine.inc' l='581' u='r' c='sbackref'/>
<use f='llvm/llvm/lib/Support/regengine.inc' l='598' u='r' c='sbackref'/>
<use f='llvm/llvm/lib/Support/regengine.inc' l='634' u='r' c='sbackref'/>
<use f='llvm/llvm/lib/Support/regengine.inc' l='639' u='r' c='sbackref'/>
<use f='llvm/llvm/lib/Support/regengine.inc' l='640' u='r' c='sbackref'/>
<use f='llvm/llvm/lib/Support/regengine.inc' l='698' u='r' c='sfast'/>
<use f='llvm/llvm/lib/Support/regengine.inc' l='712' u='r' c='sfast'/>
<use f='llvm/llvm/lib/Support/regengine.inc' l='715' u='r' c='sfast'/>
<use f='llvm/llvm/lib/Support/regengine.inc' l='717' u='r' c='sfast'/>
<use f='llvm/llvm/lib/Support/regengine.inc' l='720' u='r' c='sfast'/>
<use f='llvm/llvm/lib/Support/regengine.inc' l='724' u='r' c='sfast'/>
<use f='llvm/llvm/lib/Support/regengine.inc' l='738' u='r' c='sfast'/>
<use f='llvm/llvm/lib/Support/regengine.inc' l='750' u='r' c='sfast'/>
<use f='llvm/llvm/lib/Support/regengine.inc' l='785' u='r' c='sslow'/>
<use f='llvm/llvm/lib/Support/regengine.inc' l='795' u='r' c='sslow'/>
<use f='llvm/llvm/lib/Support/regengine.inc' l='798' u='r' c='sslow'/>
<use f='llvm/llvm/lib/Support/regengine.inc' l='800' u='r' c='sslow'/>
<use f='llvm/llvm/lib/Support/regengine.inc' l='803' u='r' c='sslow'/>
<use f='llvm/llvm/lib/Support/regengine.inc' l='807' u='r' c='sslow'/>
<use f='llvm/llvm/lib/Support/regengine.inc' l='821' u='r' c='sslow'/>
<use f='llvm/llvm/lib/Support/regengine.inc' l='835' u='r' c='sslow'/>
<offset>0</offset>
